// Copyright (C) 2012-2026 Zammad Foundation, https://zammad-foundation.org/

import type { RouteRecordRaw } from 'vue-router'

const route: RouteRecordRaw[] = [
  {
    path: '/manage',
    alias: [
      '/desktop/settings',
      '/manage/settings',
      '/settings',
      '/desktop/system',
      '/manage/system',
      '/system',
    ],
    name: 'ManageSettings',
    component: () => import('./views/Manage.vue'),
    meta: {
      title: __('Administration'),
      icon: 'gear',
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*'],
      level: 1,
      order: 2,
      pageKey: 'manage',
      permanentItem: true,
    },
  },
  {
    path: '/manage/users',
    name: 'ManageUsers',
    component: () => import('./views/Users.vue'),
    meta: {
      title: __('Users Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*'],
      level: 3,
      pageKey: 'manage-users',
    },
  },
  {
    path: '/manage/groups',
    name: 'ManageGroups',
    component: () => import('./views/Groups.vue'),
    meta: {
      title: __('Groups Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*'],
      level: 3,
      pageKey: 'manage-groups',
    },
  },
  {
    path: '/manage/roles',
    name: 'ManageRoles',
    component: () => import('./views/Roles.vue'),
    meta: {
      title: __('Roles Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.role'],
      level: 3,
      pageKey: 'manage-roles',
    },
  },
  {
    path: '/manage/organizations',
    name: 'ManageOrganizations',
    component: () => import('./views/Organizations.vue'),
    meta: {
      title: __('Organizations Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*'],
      level: 3,
      pageKey: 'manage-organizations',
    },
  },
  {
    path: '/manage/overviews',
    name: 'ManageOverviews',
    component: () => import('./views/Overviews.vue'),
    meta: {
      title: __('Overviews Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*'],
      level: 3,
      pageKey: 'manage-overviews',
    },
  },
  {
    path: '/manage/text_modules',
    name: 'ManageTextModules',
    component: () => import('./views/TextModules.vue'),
    meta: {
      title: __('Text Modules Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*'],
      level: 3,
      pageKey: 'manage-text-modules',
    },
  },
  {
    path: '/manage/macros',
    name: 'ManageMacros',
    component: () => import('./views/Macros.vue'),
    meta: {
      title: __('Macros Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*'],
      level: 3,
      pageKey: 'manage-macros',
    },
  },
  {
    path: '/manage/templates',
    name: 'ManageTemplates',
    component: () => import('./views/Templates.vue'),
    meta: {
      title: __('Templates Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*'],
      level: 3,
      pageKey: 'manage-templates',
    },
  },
  {
    path: '/manage/tags',
    name: 'ManageTags',
    component: () => import('./views/Tags.vue'),
    meta: {
      title: __('Tags Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.tag'],
      level: 3,
      pageKey: 'manage-tags',
    },
  },
  {
    path: '/manage/checklists',
    name: 'ManageChecklists',
    component: () => import('./views/Checklists.vue'),
    meta: {
      title: __('Checklists Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*'],
      level: 3,
      pageKey: 'manage-checklists',
    },
  },
  {
    path: '/manage/slas',
    name: 'ManageSlas',
    component: () => import('./views/Slas.vue'),
    meta: {
      title: __('SLAs Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*'],
      level: 3,
      pageKey: 'manage-slas',
    },
  },
  {
    path: '/manage/triggers',
    name: 'ManageTriggers',
    component: () => import('./views/Triggers.vue'),
    meta: {
      title: __('Triggers Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*'],
      level: 3,
      pageKey: 'manage-triggers',
    },
  },
  {
    path: '/manage/webhooks',
    name: 'ManageWebhooks',
    component: () => import('./views/Webhooks.vue'),
    meta: {
      title: __('Webhooks Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*'],
      level: 3,
      pageKey: 'manage-webhooks',
    },
  },
  {
    path: '/manage/public_links',
    name: 'ManagePublicLinks',
    component: () => import('./views/PublicLinks.vue'),
    meta: {
      title: __('Public Links Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.public_links'],
      level: 3,
      pageKey: 'manage-public-links',
    },
  },
  {
    path: '/manage/calendars',
    name: 'ManageCalendars',
    component: () => import('./views/Calendars.vue'),
    meta: {
      title: __('Calendars Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*'],
      level: 3,
      pageKey: 'manage-calendars',
    },
  },
  {
    path: '/manage/report_profiles',
    name: 'ManageReportProfiles',
    component: () => import('./views/ReportProfiles.vue'),
    meta: {
      title: __('Report Profiles Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.report_profile'],
      level: 3,
      pageKey: 'manage-report-profiles',
    },
  },
  {
    path: '/manage/time_accounting',
    name: 'ManageTimeAccounting',
    component: () => import('./views/TimeAccounting.vue'),
    meta: {
      title: __('Time Accounting Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.time_accounting'],
      level: 3,
      pageKey: 'manage-time-accounting',
    },
  },
  {
    path: '/manage/knowledge_base',
    name: 'ManageKnowledgeBase',
    component: () => import('./views/KnowledgeBase.vue'),
    meta: {
      title: __('Knowledge Base Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.knowledge_base'],
      level: 3,
      pageKey: 'manage-knowledge-base',
    },
  },
  {
    path: '/manage/channels/web',
    name: 'ManageChannelWeb',
    component: () => import('./views/ChannelWeb.vue'),
    meta: {
      title: __('Web Channel Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.channel_web'],
      level: 3,
      pageKey: 'manage-channel-web',
    },
  },
  {
    path: '/manage/channels/email',
    name: 'ManageChannelEmail',
    component: () => import('./views/ChannelEmail.vue'),
    meta: {
      title: __('Email Channel Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.channel_email'],
      level: 3,
      pageKey: 'manage-channel-email',
    },
  },
  {
    path: '/manage/channels/sms',
    name: 'ManageChannelSms',
    component: () => import('./views/ChannelSms.vue'),
    meta: {
      title: __('SMS Channel Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.channel_sms'],
      level: 3,
      pageKey: 'manage-channel-sms',
    },
  },
  {
    path: '/manage/channels/chat',
    name: 'ManageChannelChat',
    component: () => import('./views/ChannelChat.vue'),
    meta: {
      title: __('Chat Channel Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.channel_chat'],
      level: 3,
      pageKey: 'manage-channel-chat',
    },
  },
  {
    path: '/manage/channels/google',
    name: 'ManageChannelGoogle',
    component: () => import('./views/ChannelGoogle.vue'),
    meta: {
      title: __('Google Channel Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.channel_google'],
      level: 3,
      pageKey: 'manage-channel-google',
    },
  },
  {
    path: '/manage/channels/microsoft365',
    name: 'ManageChannelMicrosoft365',
    component: () => import('./views/ChannelMicrosoft365.vue'),
    meta: {
      title: __('Microsoft 365 Channel Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.channel_microsoft365'],
      level: 3,
      pageKey: 'manage-channel-microsoft365',
    },
  },
  {
    path: '/manage/channels/microsoft_graph',
    name: 'ManageChannelMicrosoftGraph',
    component: () => import('./views/ChannelMicrosoftGraph.vue'),
    meta: {
      title: __('Microsoft 365 Graph Channel Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.channel_microsoft_graph'],
      level: 3,
      pageKey: 'manage-channel-microsoft-graph',
    },
  },
  {
    path: '/manage/channels/facebook',
    name: 'ManageChannelFacebook',
    component: () => import('./views/ChannelFacebook.vue'),
    meta: {
      title: __('Facebook Channel Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.channel_facebook'],
      level: 3,
      pageKey: 'manage-channel-facebook',
    },
  },
  {
    path: '/manage/channels/telegram',
    name: 'ManageChannelTelegram',
    component: () => import('./views/ChannelTelegram.vue'),
    meta: {
      title: __('Telegram Channel Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.channel_telegram'],
      level: 3,
      pageKey: 'manage-channel-telegram',
    },
  },
  {
    path: '/manage/channels/whatsapp',
    name: 'ManageChannelWhatsapp',
    component: () => import('./views/ChannelWhatsapp.vue'),
    meta: {
      title: __('WhatsApp Channel Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.channel_whatsapp'],
      level: 3,
      pageKey: 'manage-channel-whatsapp',
    },
  },
  {
    path: '/manage/channels/form',
    name: 'ManageChannelForm',
    component: () => import('./views/ChannelForm.vue'),
    meta: {
      title: __('Form Channel Management'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.channel_formular'],
      level: 3,
      pageKey: 'manage-channel-form',
    },
  },
  {
    path: '/manage/settings/branding',
    name: 'ManageSettingBranding',
    component: () => import('./views/SettingBranding.vue'),
    meta: {
      title: __('Branding Settings'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.branding'],
      level: 3,
      pageKey: 'manage-setting-branding',
    },
  },
  {
    path: '/manage/settings/security',
    name: 'ManageSettingSecurity',
    component: () => import('./views/SettingSecurity.vue'),
    meta: {
      title: __('Security Settings'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.security'],
      level: 3,
      pageKey: 'manage-setting-security',
    },
  },
  {
    path: '/manage/settings/ticket',
    name: 'ManageSettingTicket',
    component: () => import('./views/SettingTicket.vue'),
    meta: {
      title: __('Ticket Settings'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.ticket'],
      level: 3,
      pageKey: 'manage-setting-ticket',
    },
  },
  {
    path: '/manage/settings/system',
    name: 'ManageSettingSystem',
    component: () => import('./views/SettingSystem.vue'),
    meta: {
      title: __('System Settings'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.system'],
      level: 3,
      pageKey: 'manage-setting-system',
    },
  },
  {
    path: '/manage/system/integrations',
    alias: ['/system/integration', '/system/integrations'],
    name: 'ManageSystemIntegrations',
    component: () => import('./views/SystemIntegrations.vue'),
    meta: {
      title: __('System Integrations'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.integration'],
      level: 3,
      pageKey: 'manage-system-integrations',
    },
  },
  {
    path: '/manage/system/objects',
    alias: ['/system/object_manager', '/system/objects'],
    name: 'ManageSystemObjects',
    component: () => import('./views/SystemObjects.vue'),
    meta: {
      title: __('Object Manager'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.object'],
      level: 3,
      pageKey: 'manage-system-objects',
    },
  },
  {
    path: '/manage/system/core_workflows',
    alias: ['/system/core_workflow', '/system/core_workflows'],
    name: 'ManageSystemCoreWorkflows',
    component: () => import('./views/SystemCoreWorkflows.vue'),
    meta: {
      title: __('Core Workflows'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.core_workflow'],
      level: 3,
      pageKey: 'manage-system-core-workflows',
    },
  },
  {
    path: '/manage/system/api',
    alias: ['/system/api'],
    name: 'ManageSystemApi',
    component: () => import('./views/SystemApi.vue'),
    meta: {
      title: __('API & Applications'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.api'],
      level: 3,
      pageKey: 'manage-system-api',
    },
  },
  {
    path: '/manage/system/monitoring',
    alias: ['/system/monitoring'],
    name: 'ManageSystemMonitoring',
    component: () => import('./views/SystemMonitoring.vue'),
    meta: {
      title: __('System Monitoring'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.monitoring'],
      level: 3,
      pageKey: 'manage-system-monitoring',
    },
  },
  {
    path: '/manage/system/translations',
    alias: ['/system/translation', '/system/translations'],
    name: 'ManageSystemTranslations',
    component: () => import('./views/SystemTranslations.vue'),
    meta: {
      title: __('Translations'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.translation'],
      level: 3,
      pageKey: 'manage-system-translations',
    },
  },
  {
    path: '/manage/system/maintenance',
    alias: ['/system/maintenance'],
    name: 'ManageSystemMaintenance',
    component: () => import('./views/SystemMaintenance.vue'),
    meta: {
      title: __('System Maintenance'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.maintenance'],
      level: 3,
      pageKey: 'manage-system-maintenance',
    },
  },
  {
    path: '/manage/system/data_privacy',
    alias: ['/system/data_privacy'],
    name: 'ManageSystemDataPrivacy',
    component: () => import('./views/SystemDataPrivacy.vue'),
    meta: {
      title: __('Data Privacy'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.data_privacy'],
      level: 3,
      pageKey: 'manage-system-data-privacy',
    },
  },
  {
    path: '/manage/system/backup',
    alias: ['/system/backup'],
    name: 'ManageSystemBackup',
    component: () => import('./views/SystemBackup.vue'),
    meta: {
      title: __('System Backup'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.system'],
      level: 3,
      pageKey: 'manage-system-backup',
    },
  },
  {
    path: '/manage/system/packages',
    alias: ['/system/package', '/system/packages'],
    name: 'ManageSystemPackages',
    component: () => import('./views/SystemPackages.vue'),
    meta: {
      title: __('System Packages'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.package'],
      level: 3,
      pageKey: 'manage-system-packages',
    },
  },
  {
    path: '/manage/system/sessions',
    alias: ['/system/sessions'],
    name: 'ManageSystemSessions',
    component: () => import('./views/SystemSessions.vue'),
    meta: {
      title: __('User Sessions'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.session'],
      level: 3,
      pageKey: 'manage-system-sessions',
    },
  },
  {
    path: '/manage/system/version',
    alias: ['/system/version'],
    name: 'ManageSystemVersion',
    component: () => import('./views/SystemVersion.vue'),
    meta: {
      title: __('System Version'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*'],
      level: 3,
      pageKey: 'manage-system-version',
    },
  },
  {
    path: '/manage/system/system_report',
    alias: ['/manage/system/system-report', '/system/system_report', '/system/system-report'],
    name: 'ManageSystemReport',
    component: () => import('./views/SystemReport.vue'),
    meta: {
      title: __('System Report'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.system_report'],
      level: 3,
      pageKey: 'manage-system-report',
    },
  },
  {
    path: '/manage/ai/provider',
    alias: ['/ai/provider'],
    name: 'ManageAiProvider',
    component: () => import('./views/AiProvider.vue'),
    meta: {
      title: __('AI Provider'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.ai_provider'],
      level: 3,
      pageKey: 'manage-ai-provider',
    },
  },
  {
    path: '/manage/ai/ticket_summary',
    alias: ['/ai/ticket_summary'],
    name: 'ManageAiTicketSummary',
    component: () => import('./views/AiTicketSummary.vue'),
    meta: {
      title: __('Ticket Summary'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.ai_assistance_ticket_summary'],
      level: 3,
      pageKey: 'manage-ai-ticket-summary',
    },
  },
  {
    path: '/manage/ai/text_tools',
    alias: ['/manage/ai/writing_assistant', '/ai/text_tools', '/ai/writing_assistant'],
    name: 'ManageAiWritingAssistant',
    component: () => import('./views/AiWritingAssistant.vue'),
    meta: {
      title: __('Writing Assistant'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.ai_assistance_text_tools'],
      level: 3,
      pageKey: 'manage-ai-writing-assistant',
    },
  },
  {
    path: '/manage/ai/ai_agents',
    alias: ['/manage/ai/agents', '/ai/ai_agents', '/ai/agents'],
    name: 'ManageAiAgents',
    component: () => import('./views/AiAgents.vue'),
    meta: {
      title: __('AI Agents'),
      requiresAuth: true,
      requiredPermission: ['admin', 'admin.*', 'admin.ai_agent'],
      level: 3,
      pageKey: 'manage-ai-agents',
    },
  },
]

export default route
